#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u 'ruucm-working':'cm173173' https://api.github.com/user/repos?access_token=95087e34025325a38dd106915d05f20abb0b7866 -d "{\"name\":\"$repo_name\"}"
